# This is the Blog typeDef for GraphQL

type Blog{
    id: ID!,
    title: String,
    content:String,
    introduction: String,
    createTime: String,
    lastUpdateTime: String
}

input InputBlog{
    id: String,
    title: String,
    introduction: String,
    content:String
}

type Query {
    getBlogs: [Blog],
    getBlogById(id:String): Blog
}

type Mutation {
    createBlog(blog:InputBlog): Blog,
    updateBlog(blog:InputBlog): Blog,
    deleteBlog(id:String): Blog
}

scalar DateScalar

scalar JsonScalar